name: Publish Dev Release

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string

jobs:
  publish:
    name: Publish ${{ inputs.package }} Dev Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            package: ${{ inputs.package }}
      - uses: actions/setup-node@v4
        if: ${{ steps.changes.outputs.package == 'true' }}
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
          registry-url: "https://registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn install --frozen-lockfile
        if: ${{ steps.changes.outputs.package == 'true' }}
        working-directory: ${{ inputs.package }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Get current version 
        if: ${{ steps.changes.outputs.package == 'true' }}
        id: version
        working-directory: ${{ inputs.package }}
        run: |
          VERSION=$(node -p "require('./package.json').version")
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          DEV_VERSION="${VERSION}-dev.${SHORT_SHA}"
          echo "dev_version=${DEV_VERSION}" >> $GITHUB_OUTPUT
          echo "Publishing dev version: ${DEV_VERSION}"
      - name: Update package.json with dev version
        if: ${{ steps.changes.outputs.package == 'true' }}
        working-directory: ${{ inputs.package }}
        run: |
          npm pkg set version="${{ steps.version.outputs.dev_version }}"
      - name: Publish dev release
        if: ${{ steps.changes.outputs.package == 'true' }}
        working-directory: ${{ inputs.package }}
        run: |
          cp "$NPM_CONFIG_USERCONFIG" ~/.npmrc
          yarn publish --tag dev --non-interactive
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
