[tool.poetry]
name = "python-pkg"
version = "0.1.0"
description = "Test"
authors = ["Aaron Teo <aaron@mytos.bio>"]

[tool.poetry.dependencies]
python = "^3.9.17"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
